# Generated by Django 2.2.2 on 2019-06-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
