# Generated by Django 2.2.2 on 2019-06-06 06:41

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='billentry',
            name='category',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='billentry',
            name='cost',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(500000)]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='alt_phone',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
