# Generated by Django 2.2.2 on 2019-06-06 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billentry',
            name='cost',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(500000)]),
        ),
    ]
