# Generated by Django 2.2.2 on 2019-06-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190606_1358'),
        ('main', '0002_auto_20190606_1211'),
    ]

    operations = [
    ]
