# Generated by Django 2.2.2 on 2019-06-11 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_20190607_1447'),
        ('main', '0003_remove_billentry_parent'),
    ]

    operations = [
    ]
