# Generated by Django 2.2.2 on 2019-06-13 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_billentry_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='items',
            field=models.ManyToManyField(related_name='billings', to='main.BillEntry'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='main.Patient'),
        ),
    ]
