# Generated by Django 2.2.2 on 2019-06-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190613_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billentry',
            name='category',
            field=models.CharField(max_length=32),
        ),
    ]
