# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190613_1243'),
        ('main', '0004_merge_20190611_1034'),
    ]

    operations = [
    ]
