# Generated by Django 2.2.2 on 2019-06-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190613_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
