# Generated by Django 2.2.2 on 2019-06-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bill_completed'),
        ('main', '0002_auto_20190606_1358'),
        ('main', '0006_bill_completed0'),
    ]

    operations = [
    ]
