# Generated by Django 2.2.2 on 2019-07-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190705_1423'),
        ('main', '0008_auto_20190707_1820'),
    ]

    operations = [
    ]
